name: Build and Upload Cheshire

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  setup_python:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use a specific version if needed

  install_dependencies:
    runs-on: ubuntu-latest
    needs: setup_python
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake autotools-dev curl python3 python3-pip \
                                  libmpc-dev libmpfr-dev libgmp-dev gawk build-essential \
                                  bison flex texinfo gperf libtool patchutils bc \
                                  zlib1g-dev libexpat-dev ninja-build git cmake \
                                  libglib2.0-dev cargo

  clone_cheshire:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Clone Cheshire repository
        run: |
          cargo install bender
          git clone https://github.com/pulp-platform/cheshire.git
          cd cheshire
          git checkout mp/ara-pulpv1
          bender checkout

  build_linux_meta:
    runs-on: ubuntu-latest
    needs: clone_cheshire
    steps:
      - name: Build Linux meta
        run: |
          export CHS_ROOT=$(pwd)
          export ARA_ROOT=$(bender -d ${CHS_ROOT} path ara)
          cd ${ARA_ROOT}/cheshire/sw

          export RVV_KERNELS="hello_world-linux fmatmul-linux fconv3d-linux jacobi2d-linux fdotproduct-linux"
          make ${RVV_KERNELS}
          make linux-img
          cd ..
          make BOARD=vcu118

  upload_artifact:
    runs-on: ubuntu-latest
    needs: build_linux_meta
    steps:
      - name: Upload Cheshire directory
        uses: actions/upload-artifact@v4
        with:
          name: cheshire-artifact
          path: cheshire
