name: ArtifactDOwnload

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'ArtifactSaveTester'
        required: true
        default: 'yes'

jobs:
  create_and_save_artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Create Trap File
      run: |
        echo "This is a trap file." > trapfile.txt
        ls -R  # Print the directory structure for debugging purposes

    - name: Save as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: trapfile
        path: trapfile

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: trapfile
        path: trapfile/files

