name: Build and Test PULP Platform ARA

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'ArtifactSaveTester'
        required: true
        default: 'yes'
jobs:
  set_up_toolchain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up RISC-V toolchain
      run: |
        cd ara
        git submodule update --init --recursive
        git submodule sync --recursive
        make toolchain-llvm
        make riscv-isa-sim
        make verilator

  build_hello_world:
    runs-on: ubuntu-latest
    needs: set_up_toolchain

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Test Hello World
      run: |
        cd ara/apps
        make bin/hello_world
        make bin/hello_world.spike
        make spike-run-hello_world

  run_riscv_tests:
    runs-on: ubuntu-latest
    needs: set_up_toolchain

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run RISC-V Tests
      run: |
        cd ara/apps
        make riscv_tests

  set_up_hardware:
    runs-on: ubuntu-latest
    needs: set_up_toolchain

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up hardware
      run: |
        cd ara/hardware
        make update

  compile_hardware:
    runs-on: ubuntu-latest
    needs: set_up_hardware

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Compile hardware
      run: |
        cd ara/hardware
        make compile

  run_simulation_hello_world:
    runs-on: ubuntu-latest
    needs: compile_hardware

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run simulation with hello_world
      run: |
        cd ara/hardware
        app=hello_world make sim

  run_simulation_custom_binary:
    runs-on: ubuntu-latest
    needs: compile_hardware

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run simulation with custom binary
      run: |
        cd ara/hardware
        preload=/some_path/some_binary make sim

  run_simulation_no_gui:
    runs-on: ubuntu-latest
    needs: compile_hardware

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run simulation without GUI
      run: |
        cd ara/hardware
        app=hello_world make simc
