name: Build and Test PULP Platform ARA

on:
  workflow_dispatch:
    inputs:
      trigger-build:
        description: 'Manually trigger the build'
        required: true

jobs:
  set_up_toolchain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up RISC-V toolchain
      run: |
        git clone https://github.com/pulp-platform/ara.git
        cd ara
        git submodule update --init --recursive
        git submodule sync --recursive
        make toolchain-llvm
        make riscv-isa-sim
        make verilator

    - name: Upload toolchain artifacts
      uses: actions/upload-artifact@v3
      with:
        name: toolchain-artifacts
        path: ara/path/to/toolchain/artifacts  # Update with the actual path to toolchain artifacts

  build_hello_world:
    runs-on: ubuntu-latest
    needs: set_up_toolchain

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and Test Hello World
      run: |
        cd ara/apps
        make bin/hello_world
        make bin/hello_world.spike
        make spike-run-hello_world

    - name: Upload hello_world artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hello-world-artifacts
        path: ara/path/to/hello_world/artifacts  # Update with the actual path to hello_world artifacts

  run_riscv_tests:
    runs-on: ubuntu-latest
    needs: set_up_toolchain

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run RISC-V Tests
      run: |
        cd ara/apps
        make riscv_tests

    - name: Upload riscv_tests artifacts
      uses: actions/upload-artifact@v3
      with:
        name: riscv-tests-artifacts
        path: ara/path/to/riscv_tests/artifacts  # Update with the actual path to riscv_tests artifacts

  set_up_hardware:
    runs-on: ubuntu-latest
    needs: set_up_toolchain

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up hardware
      run: |
        cd ara/hardware
        make update

    - name: Upload hardware artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hardware-artifacts
        path: ara/path/to/hardware/artifacts  # Update with the actual path to hardware artifacts

  compile_hardware:
    runs-on: ubuntu-latest
    needs: set_up_hardware

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile hardware
      run: |
        cd ara/hardware
        make compile

    - name: Upload compiled-hardware artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compiled-hardware-artifacts
        path: ara/path/to/compiled_hardware/artifacts  # Update with the actual path to compiled_hardware artifacts

  run_simulation_hello_world:
    runs-on: ubuntu-latest
    needs: compile_hardware

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run simulation with hello_world
      run: |
        cd ara/hardware
        app=hello_world make sim

    - name: Upload simulation-hello_world artifacts
      uses: actions/upload-artifact@v3
      with:
        name: simulation-hello_world-artifacts
        path: ara/path/to/simulation_hello_world/artifacts  # Update with the actual path to simulation_hello_world artifacts

  run_simulation_custom_binary:
    runs-on: ubuntu-latest
    needs: compile_hardware

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run simulation with custom binary
      run: |
        cd ara/hardware
        preload=/some_path/some_binary make sim

    - name: Upload simulation-custom_binary artifacts
      uses: actions/upload-artifact@v3
      with:
        name: simulation-custom_binary-artifacts
        path: ara/path/to/simulation_custom_binary/artifacts  # Update with the actual path to simulation_custom_binary artifacts

  run_simulation_no_gui:
    runs-on: ubuntu-latest
    needs: compile_hardware

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run simulation without GUI
      run: |
        cd ara/hardware
        app=hello_world make simc

    - name: Upload simulation-no_gui artifacts
      uses: actions/upload-artifact@v3
      with:
        name: simulation-no_gui-artifacts
        path: ara/path/to/simulation_no_gui/artifacts  # Update with the actual path to simulation_no_gui artifacts
