name: Build and Release RISC-V Toolchain

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Run the RISC-V Toolchain build'
        required: true
        default: 'yes'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev

      - name: Build RISC-V Toolchain
        run: |
          git clone https://github.com/riscv/riscv-gnu-toolchain
          cd riscv-gnu-toolchain
          ./configure --prefix=/opt/riscv
          make -j $(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: riscv-toolchain
          path: /opt/riscv

  release:
    needs: build  # Ensure 'build' job is completed before running this job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: riscv-toolchain
          path: /opt/riscv

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0  # Specify the tag name for the release
          release_name: Release 1.0  # Specify the release name
          body: |
            Release notes for version 1.0

      - name: Upload Release Artifact
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /opt/riscv
          asset_name: riscv-toolchain
          asset_content_type: application/zip  # Change this based on the actual content type


