name: Build RISC-V Toolchain

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Run the RISC-V Toolchain build'
        required: true
        default: 'yes'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install -y autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev

      - name: Build RISC-V Toolchain
        run: |
          git clone https://github.com/riscv/riscv-gnu-toolchain
          cd riscv-gnu-toolchain
          ./configure --prefix=/opt/riscv
          make -j32

      - name: Move Toolchain to Repository Directory
        run: mv riscv-gnu-toolchain /opt/riscv

      - name: Check for Changes
        id: check_changes
        run: |
          if ! git diff --exit-code; then
            echo "Changes found"
          else
            echo "No changes"
            exit 1
          fi

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.return-code == '0'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add RISC-V Toolchain"
          git push origin HEAD:$GITHUB_REF

      - name: Create Builds Directory
        run: mkdir -p builds

      - name: Move New File to Builds Directory
        run: mv /opt/riscv builds/

      - name: Commit and Push New File
        run: |
          git add builds/
          git commit -m "Add RISC-V Toolchain Binary"
          git push origin HEAD:$GITHUB_REF
