name: Generate Random Numbers

on:
  workflow_dispatch:
    inputs:
      generate-numbers:
        description: 'Generate random numbers manually'
        default: 'true'

jobs:
  generate_numbers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate random numbers
      run: |
        # Use a scripting language to generate random numbers, for example, using Python
        python -c "import random; numbers = [random.randint(1, 100) for _ in range(10)]; print(numbers)" > random_numbers.txt

    - name: Display generated numbers
      run: cat random_numbers.txt

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add random_numbers.txt
        git commit -m "Generate random numbers"
        git push
